# File: .github/workflows/build-and-deploy.yml

name: Build and Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: toandnseta/demo-cicd:main

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy to Ubuntu Server
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          # Xóa container đang chạy
          docker ps -q --filter "name=demo-cicd" | xargs -r docker stop || true
          docker ps -aq --filter "name=demo-cicd" | xargs -r docker rm || true
          # Xóa image cũ
          docker images toandnseta/demo-cicd -q | xargs -r docker rmi || true
          # Pull image mới
          docker pull toandnseta/demo-cicd:main
          # Chạy container mới
          docker run -d --name demo-cicd -p 192.168.81.156:8080:80 toandnseta/demo-cicd:main
